# Generated by Django 3.2.12 on 2023-03-27 19:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='static/products-images/default/product.png', upload_to='static/products-images/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('role', models.CharField(default='None', max_length=25)),
                ('photo', models.ImageField(default='static/cover-images/default/Login.png', upload_to='static/cover-images/%y/%m/%d/')),
                ('isPrime', models.BooleanField(default=False)),
                ('tasks', models.IntegerField(default=0)),
                ('o_tasks', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('o_projects', models.IntegerField(default=0)),
                ('fullRate', models.CharField(default='0%', max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('progress', models.CharField(default='0%', max_length=100)),
                ('description', models.TextField()),
                ('is_Done', models.BooleanField(default=False)),
                ('is_Outdated', models.BooleanField(default=False)),
                ('started_Date', models.DateField(default=datetime.datetime.now)),
                ('finishedDate', models.DateField(default=datetime.datetime.now)),
                ('deadLine', models.IntegerField(default=1)),
                ('days_left', models.IntegerField(default=0)),
                ('tasks', models.IntegerField(default=0)),
                ('o_tasks', models.IntegerField(default=0)),
                ('members', models.ManyToManyField(related_name='projectMembers', to='Main.Profile')),
                ('projectLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectLeader', to='Main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_Date', models.DateField(default=datetime.datetime.now)),
                ('modified_Date', models.DateTimeField(auto_now_add=True)),
                ('finishedDate', models.DateField(default=datetime.datetime.now)),
                ('deadLine', models.IntegerField(default=1)),
                ('is_Done', models.BooleanField(default=False)),
                ('is_Outdated', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('days_left', models.IntegerField(default=0)),
                ('progress', models.CharField(default='0%', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='Main.profile')),
                ('dependsOn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependTask', to='Main.task')),
                ('forUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TaskUser', to='Main.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='Main.project')),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggest_to', to='Main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('short', models.CharField(default='', max_length=7)),
                ('photo', models.ImageField(default='static/team-images/default/defaultTeam.jpg', upload_to='static/team-images/%y/%m/%d/')),
                ('description', models.TextField()),
                ('created_Date', models.DateField(default=datetime.datetime.now)),
                ('projects', models.IntegerField(default=0)),
                ('o_projects', models.IntegerField(default=0)),
                ('admins', models.ManyToManyField(related_name='admins', to='Main.Profile')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='Main.profile')),
                ('members', models.ManyToManyField(related_name='members', to='Main.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Team_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Team Request', max_length=15)),
                ('isUser', models.BooleanField(default=False)),
                ('created_Date', models.DateField(default=datetime.datetime.now)),
                ('teamToJoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_to_join', to='Main.team')),
                ('userToJoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_to_join', to='Main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Task_suggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_Date', models.DateField(default=datetime.datetime.now)),
                ('forUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggForUser', to='Main.profile')),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggFromUser', to='Main.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_Task', to='Main.task')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamForProject', to='Main.team'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('created_Date', models.DateField(default=datetime.datetime.now)),
                ('link', models.CharField(max_length=500)),
                ('photos', models.ManyToManyField(related_name='photos', to='Main.ProductPhoto')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamForProduct', to='Main.team')),
            ],
        ),
        migrations.CreateModel(
            name='PersonTeamRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('projectNum', models.IntegerField(default=0)),
                ('doneProjectNum', models.IntegerField(default=0)),
                ('rate', models.CharField(default='0%', max_length=100)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personTeamRate', to='Main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PersonProjectRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('tasksNum', models.IntegerField(default=0)),
                ('doneTasksNum', models.IntegerField(default=0)),
                ('rate', models.CharField(default='0%', max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personProjectRate', to='Main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Task Notification', max_length=10000)),
                ('created_Date', models.DateField(default=datetime.datetime.now)),
                ('toBeSeen', models.BooleanField(default=False)),
                ('isSeen', models.BooleanField(default=False)),
                ('forUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forUserNoty', to='Main.profile')),
            ],
        ),
    ]
