# Generated by Django 3.2.12 on 2023-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20230328_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
