# Generated by Django 3.2.12 on 2023-06-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20230411_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='statistics',
        ),
    ]
